name: CellDQ
channels:
  - defaults
  - nvidia
  - conda-forge
  - anaconda
  - bioconda
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - aom=3.6.0
  - asttokens=2.4.1
  - blas=1.0
  - blosc=1.21.3
  - bottleneck=1.3.7
  - brotli-bin=1.0.9
  - brotli=1.0.9
  - brunsli=0.1
  - bzip2=1.0.8
  - c-ares=1.19.1
  - ca-certificates=2024.7.2
  - cairo=1.16.0
  - certifi=2024.8.30
  - cfitsio=3.470
  - charls=2.2.0
  - comm=0.2.2
  - contourpy=1.2.0
  - cycler=0.11.0
  - cyrus-sasl=2.1.28
  - dav1d=1.2.1
  - dbus=1.13.18
  - debugpy=1.8.1
  - decorator=5.1.1
  - exceptiongroup=1.2.0
  - executing=2.0.1
  - expat=2.5.0
  - ffmpeg=6.1.1
  - fontconfig=2.14.2
  - fonttools=4.25.0
  - freetype=2.12.1
  - giflib=5.2.1
  - glib-tools=2.78.4
  - glib=2.78.4
  - graphite2=1.3.14
  - gst-plugins-base=1.14.1
  - gstreamer=1.14.1
  - harfbuzz=4.3.0
  - icu=58.2
  - imagecodecs=2023.1.23
  - imageio=2.33.1
  - importlib-metadata=7.1.0
  - importlib_metadata=7.1.0
  - intel-openmp=2023.1.0
  - ipykernel=6.29.3
  - ipython=8.22.2
  - jedi=0.19.1
  - jpeg=9e
  - jupyter_client=8.6.1
  - jupyter_core=5.7.2
  - jxrlib=1.1
  - kiwisolver=1.4.4
  - krb5=1.20.1
  - lame=3.100
  - lazy_loader=0.3
  - lcms2=2.12
  - ld_impl_linux-64=2.38
  - leptonica=1.82.0
  - lerc=3.0
  - libaec=1.0.4
  - libarchive=3.6.2
  - libavif=0.11.1
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libclang13=14.0.6
  - libclang=14.0.6
  - libcups=2.4.2
  - libcurl=8.5.0
  - libdeflate=1.17
  - libedit=3.1.20230828
  - libev=4.33
  - libexpat=2.5.0
  - libffi=3.4.4
  - libgcc-ng=13.2.0
  - libgfortran-ng=11.2.0
  - libgfortran5=11.2.0
  - libglib=2.78.4
  - libgomp=13.2.0
  - libiconv=1.16
  - libllvm14=14.0.6
  - libnghttp2=1.57.0
  - libnsl=2.0.1
  - libogg=1.3.5
  - libopus=1.3.1
  - libpng=1.6.39
  - libpq=12.17
  - libsodium=1.0.18
  - libsqlite=3.45.2
  - libssh2=1.10.0
  - libstdcxx-ng=13.2.0
  - libtheora=1.1.1
  - libtiff=4.5.1
  - libuuid=2.38.1
  - libvorbis=1.3.7
  - libvpx=1.13.1
  - libwebp-base=1.3.2
  - libwebp=1.3.2
  - libxcb=1.15
  - libxcrypt=4.4.36
  - libxkbcommon=1.0.1
  - libxml2=2.10.4
  - libzlib=1.2.13
  - libzopfli=1.0.3
  - llvm-openmp=14.0.6
  - lz4-c=1.9.4
  - matplotlib-base=3.8.3
  - matplotlib-inline=0.1.6
  - matplotlib=3.8.3
  - mkl-service=2.4.0
  - mkl=2023.1.0
  - mkl_fft=1.3.8
  - mkl_random=1.2.4
  - munkres=1.1.4
  - mysql=5.7.24
  - ncurses=6.4
  - nest-asyncio=1.6.0
  - networkx=3.1
  - numexpr=2.8.7
  - numpy-base=1.26.4
  - numpy=1.26.4
  - openh264=2.1.1
  - openjpeg=2.4.0
  - openssl=3.2.1
  - packaging=23.2
  - pandas=2.2.1
  - parso=0.8.4
  - pcre2=10.42
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pillow=10.2.0
  - pip=23.3.1
  - pixman=0.40.0
  - platformdirs=4.2.0
  - ply=3.11
  - prompt-toolkit=3.0.42
  - psutil=5.9.8
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pygments=2.17.2
  - pyparsing=3.0.9
  - pyqt5-sip=12.13.0
  - pyqt=5.15.10
  - python-dateutil=2.8.2
  - python-tzdata=2023.3
  - python=3.12.2
  - python_abi=3.12
  - pytz=2023.3.post1
  - pyzmq=25.1.2
  - qt-main=5.15.2
  - readline=8.2
  - scikit-image=0.22.0
  - scipy=1.12.0
  - setuptools=68.2.2
  - sip=6.7.12
  - six=1.16.0
  - snappy=1.1.10
  - sqlite=3.41.2
  - stack_data=0.6.2
  - tbb=2021.8.0
  - tesseract=5.2.0
  - tifffile=2023.4.12
  - tk=8.6.13
  - tornado=6.3.3
  - traitlets=5.14.2
  - typing_extensions=4.11.0
  - tzdata=2024a
  - wcwidth=0.2.13
  - wheel=0.41.2
  - xz=5.4.6
  - zeromq=4.3.5
  - zfp=1.0.0
  - zipp=3.17.0
  - zlib=1.2.13
  - zstd=1.5.5